import 'dart:convert';
import 'dart:io';

void main() async {
  final hiTranslations = {
    "inst_welcome_to": "आपका स्वागत है",
    "inst_shresht_library": "श्रेष्ठ लाइब्रेरी में",
    "inst_home_subtitle": "आपका डैशबोर्ड अवलोकन",
    "inst_attendance_subtitle": "चेक इन और आउट कैसे करें",
    "inst_calendar": "उपस्थिति",
    "inst_calendar_subtitle": "मासिक दृश्य, रिपोर्ट और आँकड़े",
    "inst_calendar_desc": "कैलेंडर दृश्य में अपना संपूर्ण उपस्थिति इतिहास देखें। आप अपना मासिक सारांश देख सकते हैं, अपने कुल उपस्थित दिनों को ट्रैक कर सकते हैं, और समय के साथ अपनी समयबद्धता का विश्लेषण कर सकते हैं।",
    "inst_colors": "उपस्थिति के रंग",
    "inst_colors_subtitle": "जानें कि प्रत्येक रंग का क्या अर्थ है",
    "inst_status_subtitle": "अपनी सदस्यता स्थिति को समझें",
    "inst_study_subtitle": "अपने उत्पादक घंटों को ट्रैक करें",
    "inst_header_title": "स्मार्ट तरीके से ऐप का उपयोग करने के लिए आपकी संपूर्ण मार्गदर्शिका।",
    "inst_home_part1": "होम स्क्रीन आपकी वर्तमान लाइब्रेरी स्थिति दिखाती है। उपस्थिति स्थिति विजेट आपको आपकी आज की उपस्थिति का त्वरित अवलोकन देता है। उपयोग करें ",
    "inst_home_scan_btn": "स्कैन",
    "inst_home_part2": " बटन चेक-इन और चेक-आउट के लिए क्यूआर कोड को स्कैन करने के लिए।",
    "inst_qr_desc": "क्यूआर उपस्थिति हमें आपकी उपस्थिति को सटीक रूप से चिह्नित करने में मदद करती है। निर्धारित समय के भीतर लाइब्रेरी के प्रवेश द्वार पर प्रदर्शित क्यूआर कोड को स्कैन करें।",
    "inst_qr_timing": "लाइब्रेरी का समय ",
    "inst_qr_dynamic": "(परिवर्तनीय)",
    "inst_qr_start_time": "प्रारंभ समय",
    "inst_qr_allowed_time": "अनुमत समय",
    "inst_qr_end_time": "समाप्ति समय",
    "inst_qr_rule1_title": "प्रवेश करते समय केवल एक बार स्कैन करें।",
    "inst_qr_rule1_desc": "डुप्लिकेट स्कैन की अनुमति नहीं है।",
    "inst_qr_rule2_title": "आपको निर्धारित समय के भीतर स्कैन करना होगा।",
    "inst_qr_rule2_desc1": "उसके बाद आपको ",
    "inst_qr_rule2_desc2": " के रूप में चिह्नित किया जाएगा।",
    "inst_qr_rule3_title": "यदि आप अनुमत समय के बाद देर से आते हैं, तो लाइब्रेरी स्टाफ से संपर्क करें।",
    "inst_qr_rule3_desc1": "यदि अनुमति हो तो कर्मचारी आपको मैन्युअल रूप से चिह्नित कर सकते हैं। आपकी स्थिति ",
    "inst_qr_rule3_desc2": " के रूप में दिखाई देगी।",
    "inst_qr_rule4_title": "सुनिश्चित करें कि आपका स्थान (लोकेशन) चालू है और इंटरनेट उपलब्ध है।",
    "inst_qr_how_to": "स्कैन कैसे करें?",
    "inst_qr_step1_1": "टैप करें ",
    "inst_qr_step1_2": " बटन पर।",
    "inst_qr_step2": "कैमरा अनुमति दें।",
    "inst_qr_step3": "कैमरे को क्यूआर कोड की ओर करें।",
    "inst_qr_step4": "सफलता संदेश की प्रतीक्षा करें।",
    "inst_qr_step5": "आपकी उपस्थिति दर्ज की जाएगी।",
    "inst_color_present_title": "उपस्थित",
    "inst_color_present_desc": "आपको समय पर उपस्थित चिह्नित किया गया था।",
    "inst_color_late_title": "देर",
    "inst_color_late_desc": "आपने अनुमत आगमन समय के बाद स्कैन किया।",
    "inst_color_absent_title": "अनुपस्थित",
    "inst_color_absent_desc": "आप उपस्थित नहीं हुए या अपना क्यूआर स्कैन करने में विफल रहे।",
    "inst_color_holiday_title": "अवकाश",
    "inst_color_holiday_desc": "लाइब्रेरी अवकाश के कारण बंद थी।",
    "inst_color_pending_title": "लंबित",
    "inst_color_pending_desc": "आपकी उपस्थिति स्थिति समीक्षा के लिए लंबित है।",
    "inst_status_live_title": "लाइव",
    "inst_status_live_desc": "आपके पास एक सक्रिय सदस्यता है और आप सभी सुविधाओं का उपयोग कर सकते हैं।",
    "inst_status_pending_title": "लंबित",
    "inst_status_pending_desc": "आपके सदस्यता भुगतान की कर्मचारियों द्वारा समीक्षा की जा रही है।",
    "inst_status_suspended_title": "निलंबित",
    "inst_status_suspended_desc": "आपका खाता व्यवस्थापक द्वारा अस्थायी रूप से अक्षम कर दिया गया है।",
    "inst_status_expired_title": "समाप्त",
    "inst_status_expired_desc": "आपकी सदस्यता समाप्त हो गई है। कृपया सुविधाओं तक पहुंचने के लिए नवीनीकृत करें।",
    "inst_study_desc_main": "अध्ययन क्षेत्र आपको सुंदर विश्लेषण के साथ अपने उत्पादक अध्ययन घंटों को केंद्रित करने और ट्रैक करने में मदद करता है।",
    "inst_study_start_title": "सत्र प्रारंभ करें",
    "inst_study_start_1": "शुरू करने के लिए ",
    "inst_study_start_btn": "नया सत्र प्रारंभ करें",
    "inst_study_start_2": " पर टैप करें।",
    "inst_study_pause_title": "रोकें / फिर से शुरू करें",
    "inst_study_pause_desc": "आप किसी भी समय रोक सकते हैं और फिर से शुरू कर सकते हैं।",
    "inst_study_break_title": "विश्राम का समय",
    "inst_study_break_desc": "छोटे ब्रेक लें। ऐप ब्रेक टाइम की गणना नहीं करेगा।",
    "inst_study_end_title": "सत्र समाप्त करें",
    "inst_study_end_1": "अपना सत्र समाप्त करने के लिए ",
    "inst_study_end_btn": "छोड़ें",
    "inst_study_end_2": " पर टैप करें।",
    "inst_study_analytics_title": "विश्लेषिकी",
    "inst_study_analytics_desc": "दैनिक, साप्ताहिक और मासिक अध्ययन विश्लेषण देखें।",
    "inst_study_streak_title": "फोकस स्ट्रीक",
    "inst_study_streak_desc": "अपनी स्ट्रीक बनाए रखें और अपना फोकस समय बढ़ाएं।",
    "inst_tips": "सुझाव",
    "inst_tip1": "अपने फोन को ध्यान भटकाने वाली चीजों से दूर रखें।",
    "inst_tip2": "अपनी आंखों को आराम देने के लिए ब्रेक टाइम का उपयोग करें।",
    "inst_tip3": "निरंतरता सफलता की कुंजी है।"
  };

  final guTranslations = {
    "inst_welcome_to": "સ્વાગત છે",
    "inst_shresht_library": "શ્રેષ્ઠ લાઇબ્રેરીમાં",
    "inst_home_subtitle": "તમારું ડેશબોર્ડ વિહંગાવલોકન",
    "inst_attendance_subtitle": "ચેક ઇન અને આઉટ કેવી રીતે કરવું",
    "inst_calendar": "હાજરી",
    "inst_calendar_subtitle": "માસિક દૃશ્ય, અહેવાલો અને આંકડા",
    "inst_calendar_desc": "કેલેન્ડર દૃશ્યમાં તમારો સંપૂર્ણ હાજરીનો ઇતિહાસ જુઓ. તમે તમારો માસિક સારાંશ જોઈ શકો છો, તમારા કુલ હાજર દિવસોને ટ્રૅક કરી શકો છો અને સમય જતાં તમારી સમયબદ્ધતાનું વિશ્લેષણ કરી શકો છો.",
    "inst_colors": "હાજરીના રંગો",
    "inst_colors_subtitle": "જાણો દરેક રંગનો અર્થ શું છે",
    "inst_status_subtitle": "તમારી સદસ્યતાની સ્થિતિ સમજો",
    "inst_study_subtitle": "તમારા ઉત્પાદક કલાકોને ટ્રૅક કરો",
    "inst_header_title": "સ્માર્ટ રીતે એપ્લિકેશનનો ઉપયોગ કરવા માટેની તમારી સંપૂર્ણ માર્ગદર્શિકા.",
    "inst_home_part1": "હોમ સ્ક્રીન તમારી વર્તમાન લાઇબ્રેરી સ્થિતિ દર્શાવે છે. હાજરી સ્થિતિ વિજેટ તમને તમારી આજની હાજરીનું ઝડપી વિહંગાવલોકન આપે છે. ચેક-ઇન અને ચેક-આઉટ માટે ક્યૂઆર કોડ સ્કેન કરવા માટે ",
    "inst_home_scan_btn": "સ્કેન",
    "inst_home_part2": " બટનનો ઉપયોગ કરો.",
    "inst_qr_desc": "ક્યૂઆર હાજરી અમને તમારી હાજરીને સચોટ રીતે ચિહ્નિત કરવામાં મદદ કરે છે. નિર્ધારિત સમયની અંદર લાઇબ્રેરીના પ્રવેશદ્વાર પર પ્રદર્શિત ક્યૂઆર કોડને સ્કેન કરો.",
    "inst_qr_timing": "લાઇબ્રેરીનો સમય ",
    "inst_qr_dynamic": "(પરિવર્તનશીલ)",
    "inst_qr_start_time": "પ્રારંભ સમય",
    "inst_qr_allowed_time": "અનુમત સમય",
    "inst_qr_end_time": "સમાપ્તિ સમય",
    "inst_qr_rule1_title": "પ્રવેશ કરતી વખતે ફક્ત એક જ વાર સ્કેન કરો.",
    "inst_qr_rule1_desc": "ડુપ્લિકેટ સ્કેનની મંજૂરી નથી.",
    "inst_qr_rule2_title": "તમારે નિર્ધારિત સમયમાં સ્કેન કરવું આવશ્યક છે.",
    "inst_qr_rule2_desc1": "તે પછી તમને ",
    "inst_qr_rule2_desc2": " તરીકે ચિહ્નિત કરવામાં આવશે.",
    "inst_qr_rule3_title": "જો તમે અનુમત સમય પછી મોડા આવો છો, તો લાઇબ્રેરી સ્ટાફનો સંપર્ક કરો.",
    "inst_qr_rule3_desc1": "જો પરવાનગી હોય તો સ્ટાફ તમને મેન્યુઅલી ચિહ્નિત કરી શકે છે. તમારી સ્થિતિ ",
    "inst_qr_rule3_desc2": " તરીકે દેખાશે.",
    "inst_qr_rule4_title": "ખાતરી કરો કે તમારું સ્થાન (લોકેશન) ચાલુ છે અને ઇન્ટરનેટ ઉપલબ્ધ છે.",
    "inst_qr_how_to": "સ્કેન કેવી રીતે કરવું?",
    "inst_qr_step1_1": "ટેપ કરો ",
    "inst_qr_step1_2": " બટન પર.",
    "inst_qr_step2": "કેમેરાની પરવાનગી આપો.",
    "inst_qr_step3": "કેમેરાને ક્યૂઆર કોડ તરફ પોઇન્ટ કરો.",
    "inst_qr_step4": "સફળતા સંદેશની રાહ જુઓ.",
    "inst_qr_step5": "તમારી હાજરી નોંધવામાં આવશે.",
    "inst_color_present_title": "હાજર",
    "inst_color_present_desc": "તમને સમયસર હાજર ચિહ્નિત કરવામાં આવ્યા હતા.",
    "inst_color_late_title": "મોડા",
    "inst_color_late_desc": "તમે અનુમત આગમન સમય પછી સ્કેન કર્યું.",
    "inst_color_absent_title": "ગેરહાજર",
    "inst_color_absent_desc": "તમે હાજર ન હતા અથવા તમારો ક્યૂઆર સ્કેન કરવામાં નિષ્ફળ રહ્યા.",
    "inst_color_holiday_title": "રજા",
    "inst_color_holiday_desc": "લાઇબ્રેરી રજાના કારણે બંધ હતી.",
    "inst_color_pending_title": "પેન્ડિંગ",
    "inst_color_pending_desc": "તમારી હાજરીની સ્થિતિ સમીક્ષા માટે બાકી છે.",
    "inst_status_live_title": "લાઇવ",
    "inst_status_live_desc": "તમારી પાસે સક્રિય સદસ્યતા છે અને તમે તમામ સુવિધાઓનો ઉપયોગ કરી શકો છો.",
    "inst_status_pending_title": "પેન્ડિંગ",
    "inst_status_pending_desc": "તમારી સદસ્યતા ચુકવણીની સ્ટાફ દ્વારા સમીક્ષા કરવામાં આવી રહી છે.",
    "inst_status_suspended_title": "સસ્પેન્ડ",
    "inst_status_suspended_desc": "તમારું ખાતું એડમિન દ્વારા અસ્થાયી રૂપે અક્ષમ કરવામાં આવ્યું છે.",
    "inst_status_expired_title": "સમાપ્ત",
    "inst_status_expired_desc": "તમારી સદસ્યતા સમાપ્ત થઈ ગઈ છે. કૃપા કરીને સુવિધાઓને ઍક્સેસ કરવા માટે નવીકરણ કરો.",
    "inst_study_desc_main": "સ્ટડી એરિયા તમને સુંદર એનાલિટિક્સ સાથે તમારા ઉત્પાદક અભ્યાસ કલાકોને કેન્દ્રિત કરવા અને ટ્રૅક કરવામાં મદદ કરે છે.",
    "inst_study_start_title": "સત્ર પ્રારંભ કરો",
    "inst_study_start_1": "શરૂ કરવા માટે ",
    "inst_study_start_btn": "નવું સત્ર શરૂ કરો",
    "inst_study_start_2": " પર ટેપ કરો.",
    "inst_study_pause_title": "થોભાવો / ફરી શરૂ કરો",
    "inst_study_pause_desc": "તમે કોઈપણ સમયે થોભાવી શકો છો અને ફરી શરૂ કરી શકો છો.",
    "inst_study_break_title": "વિરામનો સમય",
    "inst_study_break_desc": "ટૂંકા વિરામ લો. એપ્લિકેશન બ્રેક ટાઇમ ગણશે નહીં.",
    "inst_study_end_title": "સત્ર સમાપ્ત કરો",
    "inst_study_end_1": "તમારું સત્ર સમાપ્ત કરવા માટે ",
    "inst_study_end_btn": "છોડો",
    "inst_study_end_2": " પર ટેપ કરો.",
    "inst_study_analytics_title": "એનાલિટિક્સ",
    "inst_study_analytics_desc": "દૈનિક, સાપ્તાહિક અને માસિક અભ્યાસ વિશ્લેષણ જુઓ.",
    "inst_study_streak_title": "ફોકસ સ્ટ્રીક",
    "inst_study_streak_desc": "તમારી સ્ટ્રીક જાળવી રાખો અને તમારો ફોકસ સમય વધારો.",
    "inst_tips": "ટિપ્સ",
    "inst_tip1": "તમારા ફોનને વિચલિત થતી વસ્તુઓથી દૂર રાખો.",
    "inst_tip2": "તમારી આંખોને આરામ આપવા માટે વિરામ સમયનો ઉપયોગ કરો.",
    "inst_tip3": "સુસંગતતા એ સફળતાની ચાવી છે."
  };

  void applyTranslations(String lang, Map<String, String> translations) {
    final file = File('lib/core/l10n/app_$lang.arb');
    if (!file.existsSync()) return;
    final jsonStr = file.readAsStringSync();
    final Map<String, dynamic> data = jsonDecode(jsonStr);
    
    for (var key in translations.keys) {
      if (data.containsKey(key)) {
        data[key] = translations[key];
      }
    }
    
    const encoder = JsonEncoder.withIndent('  ');
    file.writeAsStringSync(encoder.convert(data));
  }

  applyTranslations('hi', hiTranslations);
  applyTranslations('gu', guTranslations);
  print('Translated successfully!');
}
