// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIqq6c2JpSBvCzNPbMVLeBkVh6vGEWK6I',
    appId: '1:9162751486:web:a8dc4b3be5cf5fc2f554af',
    messagingSenderId: '9162751486',
    projectId: 'shreshtlibrary',
    authDomain: 'shreshtlibrary.firebaseapp.com',
    storageBucket: 'shreshtlibrary.firebasestorage.app',
    measurementId: 'G-E0SDBV628M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUZSxfSBda86ynFo7gH3OZtOwfjTp6o-0',
    appId: '1:9162751486:android:0e309bcacc03e6e4f554af',
    messagingSenderId: '9162751486',
    projectId: 'shreshtlibrary',
    storageBucket: 'shreshtlibrary.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsrnVsyLee-HGdPkVDgn7hHIC2NsJv6ms',
    appId: '1:9162751486:ios:bb9c4a789ba44da2f554af',
    messagingSenderId: '9162751486',
    projectId: 'shreshtlibrary',
    storageBucket: 'shreshtlibrary.firebasestorage.app',
    iosBundleId: 'com.tarurinfotech.shreshtlibrary',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDsrnVsyLee-HGdPkVDgn7hHIC2NsJv6ms',
    appId: '1:9162751486:ios:bb9c4a789ba44da2f554af',
    messagingSenderId: '9162751486',
    projectId: 'shreshtlibrary',
    storageBucket: 'shreshtlibrary.firebasestorage.app',
    iosBundleId: 'com.tarurinfotech.shreshtlibrary',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDIqq6c2JpSBvCzNPbMVLeBkVh6vGEWK6I',
    appId: '1:9162751486:web:7b2f39e907fd3d71f554af',
    messagingSenderId: '9162751486',
    projectId: 'shreshtlibrary',
    authDomain: 'shreshtlibrary.firebaseapp.com',
    storageBucket: 'shreshtlibrary.firebasestorage.app',
    measurementId: 'G-MJLQMHNYBB',
  );
}
